set_property IOSTANDARD LVCMOS33 [get_ports candidate1]
set_property IOSTANDARD LVCMOS33 [get_ports candidate3]
set_property IOSTANDARD LVCMOS33 [get_ports candidate2]

set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports mode]

set_property PACKAGE_PIN F22 [get_ports mode]
set_property PACKAGE_PIN Y9 [get_ports clock]
set_property PACKAGE_PIN N15 [get_ports candidate1]
set_property PACKAGE_PIN R18 [get_ports candidate3]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets mode_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets enter_IBUF]

set_property PACKAGE_PIN G22 [get_ports {UID[0]}]
set_property PACKAGE_PIN H22 [get_ports {UID[1]}]
set_property PACKAGE_PIN F21 [get_ports {UID[2]}]
set_property PACKAGE_PIN H19 [get_ports {UID[3]}]
set_property PACKAGE_PIN H18 [get_ports {UID[4]}]
set_property PACKAGE_PIN H17 [get_ports {UID[5]}]
set_property PACKAGE_PIN M15 [get_ports enter]
set_property IOSTANDARD LVCMOS33 [get_ports enter]
set_property IOSTANDARD LVCMOS33 [get_ports {UID[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {UID[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {UID[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {UID[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {UID[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {UID[0]}]

set_property PACKAGE_PIN T18 [get_ports B1]
set_property PACKAGE_PIN P16 [get_ports B0]
set_property IOSTANDARD LVCMOS33 [get_ports B0]
set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property PACKAGE_PIN R16 [get_ports candidate2]

set_property IOSTANDARD LVCMOS33 [get_ports oled_dc_n]
set_property IOSTANDARD LVCMOS33 [get_ports oled_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports oled_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports oled_spi_data]
set_property IOSTANDARD LVCMOS33 [get_ports oled_vbat]
set_property IOSTANDARD LVCMOS33 [get_ports oled_vdd]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN U12 [get_ports oled_vdd]
set_property PACKAGE_PIN U11 [get_ports oled_vbat]
set_property PACKAGE_PIN AA12 [get_ports oled_spi_data]
set_property PACKAGE_PIN AB12 [get_ports oled_spi_clk]
set_property PACKAGE_PIN U9 [get_ports oled_reset_n]
set_property PACKAGE_PIN U10 [get_ports oled_dc_n]
